/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { convertHexToDecimal } from "./utils/convertHextoDecimal"

export function Model2(props) {
  const { nodes, materials } = useGLTF("https://cdn.shopify.com/s/files/1/0739/0206/3938/files/model2.glb");
  const { bladesColor, discColor1, discColor2 } = props

  //blades
  materials["Plaster (4)"].color.setHex(convertHexToDecimal(bladesColor))
  materials["Plaster (4)"].metalness = 0.3
  materials["Plaster (4)"].roughness = 0.1

  
  // front and back of handle
  materials["Plaster"].color.setHex(0xf1d797)
  materials["Plaster (1)"].color.setHex(0xf1d797)
  materials["Plaster (2)"].color.setHex(0x5b5958)

  //fixed stripe
  materials["Plaster (3)"].color.setHex(0x5b5958)
  materials["Plaster (53)"].color.setHex(0x5b5958)

  // 27
  materials["Plaster (5)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (27)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (28)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (29)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (30)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (31)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (32)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (33)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (34)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (35)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (36)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (37)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (38)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (39)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (40)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (41)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (42)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (43)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (44)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (45)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (46)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (47)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (48)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (49)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (50)"].color.setHex(convertHexToDecimal(discColor1))
  materials["Plaster (51)"].color.setHex(convertHexToDecimal(discColor2))
  materials["Plaster (52)"].color.setHex(convertHexToDecimal(discColor2))


  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_1.geometry}
          material={materials["Plaster (3)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_2.geometry}
          material={materials["Plaster (53)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_3.geometry}
          material={materials["Plaster (1)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_4.geometry}
          material={materials["Plaster (2)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_5.geometry}
          material={materials["Plaster (52)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_6.geometry}
          material={materials["Plaster (51)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_7.geometry}
          material={materials["Plaster (44)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_8.geometry}
          material={materials["Plaster (43)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_9.geometry}
          material={materials["Plaster (45)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_10.geometry}
          material={materials["Plaster (46)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_11.geometry}
          material={materials["Plaster (47)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_12.geometry}
          material={materials["Plaster (50)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_13.geometry}
          material={materials["Plaster (48)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_14.geometry}
          material={materials["Plaster (49)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_15.geometry}
          material={materials["Plaster (40)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_16.geometry}
          material={materials["Plaster (41)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_17.geometry}
          material={materials["Plaster (42)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_18.geometry}
          material={materials["Plaster (37)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_19.geometry}
          material={materials["Plaster (38)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_20.geometry}
          material={materials["Plaster (39)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_21.geometry}
          material={materials["Plaster (36)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_22.geometry}
          material={materials["Plaster (35)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_23.geometry}
          material={materials["Plaster (32)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_24.geometry}
          material={materials["Plaster (33)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_25.geometry}
          material={materials["Plaster (34)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_26.geometry}
          material={materials.Plaster}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_27.geometry}
          material={materials["Plaster (4)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_28.geometry}
          material={materials["Plaster (5)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_29.geometry}
          material={materials["Plaster (27)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_30.geometry}
          material={materials["Plaster (28)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_31.geometry}
          material={materials["Plaster (29)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_32.geometry}
          material={materials["Plaster (30)"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.New_Florentine_Paring_Handl_Random_33.geometry}
          material={materials["Plaster (31)"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model2.glb");
